### ISSUE TITLE
Separators between words are always the same

### ISSUE THREAD

**Issue by vhgn** [MasterGroosha/telegram-xkcd-password-generator#3]
When I generate a password with the command `/generate` *(Separators between words: Yes)* or `/generate_insane`, the symbols between words are the same every time.
Some examples of passwords I just generated:
```
?defeatism$CHARRED$seize^
*distant:LOCALITY:eight^
-AIRLINER:VIRTUOSITY:TORNADO^
```

**Comment by MasterGroosha** [comment]
Currently this is intended behaviour. I'll change it so that separators will be chosen randomly.
